### ISSUE TITLE
Adobe Photoshop Lightroom 6.0 (Windows)

### ISSUE THREAD

**Issue by christophbraun** [robinkrahl/LrMediaWiki#41]
Just uploaded an image using Lightroom 6.
All systems functioning within normal parameters.
https://commons.wikimedia.org/wiki/File:Trigonometrischer_Punkt,_Burg_Bilstein,_Hessen,_Deutschland_IMG_1138_39_40_41_42_43_44_edit.jpg

There seems to be an (unrelated?) issue with retrieving camera manufacturer and model (see metadata section).
Should read "Zeiss Planar T* 1,4/50 ZE" and "Canon EOS-1D X" instead.

**Comment by robinkrahl** [comment]
Thanks, @christophbraun, for the feedback. The EXIF issue is not related to LrMediaWiki, but caused by the EXIF library used by MediaWiki. It was also reported on the [Commons village pump](https://commons.wikimedia.org/wiki/Commons:Village_pump#Error_in_metadata_viewer.3F) and is tracked in Wikimedia Phabricator issue [T97253](https://phabricator.wikimedia.org/T97253).
