### ISSUE TITLE
Customize Description languages

### ISSUE THREAD

**Issue by toresetre** [robinkrahl/LrMediaWiki#47]

**Comment by robinkrahl** [comment]
Thanks for the bug report! I agree that it would be better to customize the fields, but I’m not sure yet whether this is possible. I’ll have a look at it. Is there a language that you’d especially like to be added?

**Comment by toresetre** [comment]
Hi Robin

Thanks for getting back to me so quickly.

First of all, thank you for a great plugin. I’m an enthusiastic photographer and believe in free distribution of information. The plugin works very well with my workflow in Lightroom and I’ve used it to add hundreds of images.

#47 It’s really not a big issue but it would make the workflow more smoothn. I’m publishing images with descriptions in Norwegian (no) or Norwegian Nynorsk (nn) mostly.

I’ve added another feature request (#48). If #48 was solved, would it be easier to customize the fields?

Regards,
Tore

**Comment by robinkrahl** [comment]
I’m happy that the plugin is useful for you. :-)

The main problem that I see with customizable description languages is consistency. As far as I see, Lightroom is not designed to handle metadata defined by the user. It *may* work (I’m not sure yet), but it might have unexpected side effects.

For example, Lightroom expects a metadata version for each set of metadata, so that it can update the catalog if necessary. I could increment this version number every time the user changes the configuration. But what if I as the plugin author add a new metadata field? The version number would be reset, and I do not know how Lightroom deals with that situation.

#48 makes this problem even more complicated. I can report the fields that I defined. But I do not know which fields you will define. So probably the plugin will work for Description (de) and Description (en), but not for your custom Description (no).

Therefore I tend to add fields for common languages instead of implementing user-defined languages. I think it would also be possible to add generic fields like ‘Description 1’ etc. and let the user decide what language would be used to generate the file description.

**Comment by Hasenlaeufer** [comment]
Is this discussion still open? Or does the field "Description (others)" fulfill the request? At this field something like e.g. "{{no|Norwegian bokmål description}}" could be used.

**Comment by toresetre** [comment]
I would like to see this enhancement. Altough there's a workaround, it adds complexity to the process and it is at risk for spelling errors.

**Comment by Hasenlaeufer** [comment]
A proposal: Let's keep the number of description fields as they are now.

Instead, provide at configuration a field which allows to select a language code like "no" or "nn". If such a setting has be done, the entry in field "Description (others)" will be surrounded with the template markers, e. g. **{{no|** User text **}}**.

Would it solve this issue?

@toresetre: You wrote "I’m publishing images with descriptions in Norwegian (no) or Norwegian Nynorsk (nn) mostly." Does this mean, you use either one of both at the same time?
My suggestion would only work for one language setting, not for several at the same time.

**Comment by toresetre** [comment]
Hi

Personally I have adapted a workflow where my Lightroom Wikimedia Commons-preset sets a couple of parameters, including setting the description field to {{no|}}. After selecting the preset I place the cursor between the | and the }} and type the description. I only use one language.

So the suggestion is basicly mimicing what I'm already doing, and the suggestion does not add much value to me personally. Others might have some benefit from this though, so I'll leave it up to you to decide.

I have to point out though that this workaround does not solve my original gripe, which is it's easy to do an error which causes the formatting to be incorrect, for instance by deleting one of the formatting characters, or placing the cursor between the wrong characters. I would probably not use the workaround. But I'm happy to test it if you implement it.

**Comment by Hasenlaeufer** [comment]
A solution proposal: The metadata field "Description (other)" should be followed by a new field "Language (other)", which can determine the language of "Description (other)".

The new field is a popup menu, starting with a default value "Other", followed by a list of most used languages, from "ar – Arabic" to "zh-hant – Chinese (Traditional)". (The list includes "nb – Norwegian Bokmål" and "nn – Norwegian Nynorsk".)

The related tooltips are:

* Description (other):
Description in another language (or in multiple other languages). Use language templates like `{{fr|Une description française}}`. Or choose for example `fr – French` at the next field “Language (other)” – then the text here may not be set in the language template {{fr|…}} – simply enter the text in French.

* Language (other):
Language of “Description (other)”. If you select a language like “fr – French”, enter the text at “Description (other)” in French. If you want to use a language not listed here of if you want to use multiple languages, choose “Other” and use at field “Description (other)” the syntax of language templates: “{{Language code|Text in another language}}”.

BTW, the language template "no" has been substituted by a redirect to "nb" – see [the redirect](https://commons.wikimedia.org/w/index.php?title=Template:No&redirect=no) and [this discussion](https://commons.wikimedia.org/wiki/Template_talk:No).

**Comment by Hasenlaeufer** [comment]
Release 0.8 provides the mentioned proposal.
Proposal: Close this issue.

**Comment by toresetre** [comment]
This has been addressed in 0.8. It can be approved though, please have a look at #97
